version: "3.8"

services:
  db:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_DB: etldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "adminpass"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - crypto-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learner"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: crypto_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - crypto-net
    depends_on:
      - db

  etl:
    build:
      context: ../etl
      dockerfile: Dockerfile
    container_name: crypto_etl
    volumes:
      - ../logs:/app/logs
    environment:
      - PG_USER=admin
      - PG_PASS=adminpass
      - PG_DB=etldb
      - PG_HOST=db
    restart: always
    networks:
      - crypto-net
    depends_on:
      - db

volumes:
  pgdata:
  pgadmindata:

networks:
  crypto-net:
    driver: bridge
